services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  teamcal:
    build: .
    environment:
      DB_SERVER: mysql
      DB_USER: teamcal
      DB_PASSWORD: teamcal
      DB_NAME: teamcal
    ports:
      - "8080:80"

volumes:
  db-data:
